---
title: "My Rough Start as a Data Scientist"
description: |
  Everyone has to start somewhere, but it's never easy.
author:
  - name: Jennifer Truong
    url: {}
date: 2022-01-17
output:
  distill::distill_article:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

It is Martin Luther King Jr. Day, 2022. Social media posts and newsletter updates from AmeriCorps about "A Day of Service" and prominent community service events have been appearing in my news feed for the past week. However, I feel guilty because the last time I participated in a community service project (let alone volunteering on MLK Day) was SIX years ago.

What was I doing instead? Overworking as a church secretary at an understaffed small church, pursuing my master's degree in the middle of a lockdown...and now? Preparing for another job interview for a *very* technical data scientist position at the state Fish and Wildlife Department.

For the past three months, my career trajectory has slightly changed. I enrolled at my environmental science master's program in fall 2019, thinking that I would return to the environmental field and work as a researcher focused on conservation. After taking classes and working on my master's thesis entirely on Zoom, I realized I was more passionate about one aspect of the research process than anything else. I enjoyed the little graphs I made in RStudio for my class assignments. Creating maps on ArcGIS and making them look pretty felt like home again.

**I love data visualization.** I love how you can take the results of your analysis and turn them into a visually effective graph or map that can convey many things all in one spot. And that's just a small part of the data analysis process!

## After Graduation 

After graduating from my master's program during the summer of 2021, I shifted my job search from "environmental scientist" jobs to simply "data scientist" jobs, hoping that my grad school experience would provide more than plenty enough to secure a job. I looked at the state career websites, I looked at the GovernmentJobs website, and I even started to look at LinkedIn's job board. How very wrong I was about the "securing a job" part.

(insert pic of LinkedIn job posting)

R and geospatial data were the two main data-related skills I used during my grad program. The job postings I saw had requirements like... 

* "proficient in Python, R, and SQL" 
* "2+ years of experience in using Tableau or other data visualization software," 
* "be able to identify KPIs" 
* "knowledgeable about A/B testing" 
* and more!

So many terms I did not know about. My confidence in my data science skills dissipated. I was basically clueless.

## The Decision to Take Online Classes

(insert pic of snowstorm)

The holiday season of 2021 felt like a huge snowstorm I needed to walk across. My health insurance situation was in limbo, my new seasonal job at Best Buy was physically wearing me out, and my job search only resulted in some interviews but no job offers. My mental health hit a new all-time low.

(TRIGGER WARNING) Add on some personal issues with family and my living situation at the time, and I felt stuck. I felt that everyone was moving on while I was chugging behind through thick layers of snow. I couldn't handle pushing on anymore. I wanted it to stop. I wanted to stop living.

If I hadn't posted a Facebook post about how I was feeling at the time and asked for help, I wouldn't have received the overflowing love and support from friends and acquaintaces I talked to and I would still be walking down that very dark path.

With this newfound strength and support, I decided to take matters into my own hands and re-learn the data skills I needed to get my self-confidence back. Around this time, an ad for the Google Data Analytics Certificate program on Coursera appeared while I was watching a Youtube video...and I clicked on it.

(insert Google Data Analytics Certificate logo)

I have tried EdX and other MOOCs before, but I never had the discipline to keep going with them. Probably because I was auditing them at the time and I didn't have to take exams or get grades.

I wanted to show some proof that I was being trained for this, so I decided to pay Coursera's monthly fee of $39.99 for getting certified. 

The first class I took was Google's "Foundations of Data, Data, Data" course, part of their certificate program. I thought I didn't need the class at first since I already had some experience in data science, but it turned out that my foundation in data science was a bit rocky than I expected.

(insert pic?)

(paragraph about that first course)

Besides Google, I also found a class about Tableau from UC Davis and I immediately enrolled in it since I saw that Tableau and other similar software was high in demand. That's when I was reassured that Tableau *does* have a free version (Tableau Public) and you didn't need to pay extra money to create dashboards

I also enrolled in some Python classes and I discovered Kaggle, which also had some online classes. The interesting thing about Kaggle is that they host competitions where you code a program for a dataset you're given and some competitions offer cash money prizes. How was I never aware of this?

(insert Kaggle datasets)

## Building a Portfolio

Throughout my research on how to get started as a data scientist, one thing has popped up in every blog article and website I come across:

**CREATE A PORTFOLIO**

Even an alumnus from my grad school who is now working as a GIS supervisor at his consulting firm told me that his portfolio helped him stand out.

And so, this leads to the creation of this website and this blog. I am uploading some old class assignments I am  proud of first, but I will post more personal projects later on. Maybe even my first Kaggle competition entry when I do enter one.