---
title: "About Me"
description: |
  A quick tidbit about who I am!
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Growing up in Orange County, California, I thought nature was always distant, never to be found in concrete sidewalks and man-made buildings. I was proven wrong once I attended college.

I earned my B.S. in environmental science in 2015 from UCLA and my master's in environmental science in 2021 from UC Santa Barbara. There, I took field trips to explore California's diverse ecosystems, learned how to bird watch, and even got to collect algae specimens for a herbarium press!

Also during this time, I learned how to use ArcGIS and RStudio, which made me realize that I want to pursue a career in data science. Currently, I am taking some online courses on Coursera, as well as buliding this data science portfolio and my data science [blog](https://jenjentro.medium.com/) on Medium.

In my free time, I enjoy hiking, visiting museums and gardens, and watching TV shows. I also stream on Twitch on occasion to celebrate my love of video games (including nature-themed ones) with others.



