---
title: "CV"
author: "Jennifer Truong"
date: "2/8/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### EDUCATION 
Master of Environmental Science and Management (Expected June 2021)
Bren School of Environmental Science & Management – University of California, Santa Barbara (UCSB)
Specialization: Conservation Planning | Focus: Environmental Data Science
Highlighted Coursework: Statistics and Data Science, Geographic Information Systems, Conservation Planning
Research: Conservation of Yellow Pine Mixed Conifer Forests in Southern California (group project)

Bachelor of Science in Environmental Science (June 2015) 
University of California, Los Angeles (UCLA)				                             
Highlighted Coursework: California Ecosystems, Introduction to Geographic Information Systems
Research: Inventorying and Monitoring Urban Insect Biodiversity for the Natural History Museum of Los Angeles County’s BioSCAN Program (group project)

ADDITIONAL EDUCATION
Geographic Information Systems (GIS) and Cartography Certificate, UCLA Extension (September 2018)
					                             
### WORK EXPERIENCE
Affiliate Streamer, Twitch, Goleta, CA (8/20 – Present)
•	Livestreamed video game playthrough for 10 hours weekly, broadcasting to 8 to 11 viewers on average
•	Engaged with viewers by addressing comments and questions mentioned in chat
•	Utilized Twitter and Instagram to announce livestreams and engage with the community
•	Create nature-themed livestreams every Tuesday for 2 hours to engage viewers and the gaming community about the environment

Ecological Assistant, United States Forest Service, Goleta, CA (7/20–9/20)
•	Streamlined Python and R code for calculating fire return interval departure (FRID) condition classes for the four national forests in Southern California
•	Analyzed US Forest Service plot and tree data through utilizing RStudio
•	Conducted a group literature review for historical and current conditions for yellow pine and mixed conifer forests in Southern California

Administrative Assistant, University Catholic Center at UCLA, Los Angeles, CA (8/16–8/19)
•	Composed 300 weekly bulletins in Microsoft Publisher to highlight student-oriented events for 10+ groups/organizations to announce news to community members
•	Compiled and edited 2 development newsletters per year for an audience of 1,500 – 3,000 community members to raise $3,000 for the year
•	Responded to 10+ emails and phone calls every day
•	Provided administrative support for 5+ professionals to support event planning by coordinating communication between students and staff and assisting with office logistics

### ADDITIONAL EXPERIENCE
Interpretive Volunteer - Natural History Museum of LA County (9/15–3/19)
Educated a variety of guests about specimens and artifacts on display throughout the museum
Outreach Student Leader - University Catholic Center at UCLA, Los Angeles, CA (9/14–6/15)
Acquired $3,000 in funding for student programming and supplies. Collaborated with eleven other team members to create programming for the student community
Studio 22 Office Assistant - UCLA Office of Residential Life, Los Angeles, CA (9/13–6/15)
Answered inquiries through 20 emails and phone calls per week. Organized paperwork for funding and TV production. Supervised a team of other office assistants with schedules and tasks.

### SKILLS & CERTIFICATES
Video Production: Livestreaming (Streamlabs OBS, Twitch)
Social Media: Facebook, Twitter, Instagram, Slack, Discord
Data Analysis & Coding: ArcGIS, QGIS, Python, R, Git
Computer: Trello, Microsoft Office (Word, Excel, PowerPoint, Publisher, & Access), Google Drive, MailChimp